name: DSE Scraper

on:
  schedule:
    # Run at 8 PM Dhaka time (14:00 UTC), only Sunday–Thursday
    - cron: "15 16 * * 0-4"
  workflow_dispatch: # allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # updated to Node.js 24 compatible

      - name: Set up Python
        uses: actions/setup-python@v5 # updated to Node.js 24 compatible
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt pandas openpyxl

      - name: Run scraper
        run: python main.py

      - name: Upload Excel output
        uses: actions/upload-artifact@v4 # updated to Node.js 24 compatible
        with:
          name: dse-data
          path: Export_Data/*.xlsx
